### ISSUE TITLE
Build Failures: Ticket Monster Analysis and Ticket Monster Release

### ISSUE THREAD

**Issue by jgammon612** [jbossdemocentral/continuous-delivery-demo#5]
![buildpipeline_build failures](https://cloud.githubusercontent.com/assets/14928349/10227267/f0bd1bb0-6831-11e5-95c5-2c7bc1ead10a.png)
# 

docker ps

[jgammon612@jgammon612 continuous-delivery-demo]$ docker ps
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS              PORTS                              NAMES
9cf682fecb97        continuousdeliverydemo_jenkins   "/usr/bin/supervisord"   40 hours ago        Up 36 minutes       0.0.0.0:8080->8080/tcp             continuousdeliverydemo_jenkins_1
8c8f73eae84c        siamaksade/nexus:2.8.1           "/opt/start-nexus.sh"    40 hours ago        Up 38 minutes       0.0.0.0:8081->8081/tcp             continuousdeliverydemo_nexus_1
e61270a01dc9        siamaksade/sonar                 "/usr/bin/supervisord"   41 hours ago        Up 38 minutes       5432/tcp, 0.0.0.0:9000->9000/tcp   continuousdeliverydemo_sonar_1
# 

Started by upstream project "ticket-monster-build" build number 3
originally caused by:
 Started by user anonymous
Building in workspace /var/lib/jenkins/workspace/ticket-monster-analysis

> git rev-parse --is-inside-work-tree # timeout=10
> Fetching changes from the remote Git repository
> git config remote.origin.url https://github.com/jbossdemocentral/continuous-delivery-demo-app.git # timeout=10
> Fetching upstream changes from https://github.com/jbossdemocentral/continuous-delivery-demo-app.git
> git --version # timeout=10
> git fetch --tags --progress https://github.com/jbossdemocentral/continuous-delivery-demo-app.git +refs/heads/_:refs/remotes/origin/_
> git rev-parse origin/master^{commit} # timeout=10
> Checking out Revision 0b020609edac992a8ba94449d78a679b9eac02e7 (origin/master)
> git config core.sparsecheckout # timeout=10
> git checkout -f 0b020609edac992a8ba94449d78a679b9eac02e7
> git rev-list 0b020609edac992a8ba94449d78a679b9eac02e7 # timeout=10
> Parsing POMs
> [ticket-monster-analysis] $ /usr/lib/jvm/java-1.7.0/bin/java -cp /var/lib/jenkins/plugins/maven-plugin/WEB-INF/lib/maven31-agent-1.5.jar:/usr/share/apache-maven/boot/plexus-classworlds-2.5.1.jar:/usr/share/apache-maven/conf/logging jenkins.maven3.agent.Maven31Main /usr/share/apache-maven /var/cache/jenkins/war/WEB-INF/lib/remoting-2.47.jar /var/lib/jenkins/plugins/maven-plugin/WEB-INF/lib/maven31-interceptor-1.5.jar /var/lib/jenkins/plugins/maven-plugin/WEB-INF/lib/maven3-interceptor-commons-1.5.jar 55040
> <===[JENKINS REMOTING CAPACITY]===>���channel started
> Executing Maven:  -B -f /var/lib/jenkins/workspace/ticket-monster-analysis/pom.xml package
> [INFO] Scanning for projects...
> [INFO] 
> [INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
> [INFO]  
> [INFO] ------------------------------------------------------------------------
> [INFO] Building ticket-monster 2.6.91-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [INFO] 
> [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ ticket-monster ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] Copying 4 resources
> [INFO] 
> [INFO] --- maven-compiler-plugin:2.3.1:compile (default-compile) @ ticket-monster ---
> [INFO] Nothing to compile - all classes are up to date
> [INFO] 
> [INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ ticket-monster ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] Copying 3 resources
> [INFO] 
> [INFO] --- maven-compiler-plugin:2.3.1:testCompile (default-testCompile) @ ticket-monster ---
> [INFO] Nothing to compile - all classes are up to date
> [INFO] 
> [INFO] --- maven-surefire-plugin:2.4.3:test (default-test) @ ticket-monster ---
> [INFO] Tests are skipped.
> [INFO] 
> [INFO] --- maven-war-plugin:2.1.1:war (default-war) @ ticket-monster ---
> [INFO] Packaging webapp
> [INFO] Assembling webapp [ticket-monster] in [/var/lib/jenkins/workspace/ticket-monster-analysis/target/ticket-monster]
> [INFO] Processing war project
> [INFO] Copying webapp resources [/var/lib/jenkins/workspace/ticket-monster-analysis/src/main/webapp]
> [INFO] Webapp assembled in [218 msecs]
> [INFO] Building war: /var/lib/jenkins/workspace/ticket-monster-analysis/target/ticket-monster.war
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 3.039 s
> [INFO] Finished at: 2015-10-01T15:36:02+00:00
> [INFO] Final Memory: 19M/293M
> [INFO] ------------------------------------------------------------------------
> Waiting for Jenkins to finish collecting data
> [JENKINS] Archiving /var/lib/jenkins/workspace/ticket-monster-analysis/pom.xml to org.jboss.examples/ticket-monster/2.6.91-SNAPSHOT/ticket-monster-2.6.91-SNAPSHOT.pom
> [JENKINS] Archiving /var/lib/jenkins/workspace/ticket-monster-analysis/target/ticket-monster.war to org.jboss.examples/ticket-monster/2.6.91-SNAPSHOT/ticket-monster-2.6.91-SNAPSHOT.war
> channel stopped
> [ticket-monster-analysis] $ /usr/share/apache-maven/bin/mvn -f /var/lib/jenkins/workspace/ticket-monster-analysis/pom.xml -e -B sonar:sonar -Dsonar.jdbc.driver=org.postgresql.Driver -Dsonar.jdbc.url=jdbc:postgresql://sonar:5432/sonar -Dsonar.host.url=http://sonar:9000 *******\* ********
> [INFO] Error stacktraces are turned on.
> [INFO] Scanning for projects...
> [INFO] Downloading: http://nexus:8081/nexus/content/groups/public/org/apache/maven/plugins/maven-metadata.xml
> [INFO] Downloading: http://nexus:8081/nexus/content/groups/public/org/codehaus/mojo/maven-metadata.xml
> [INFO] Downloaded: http://nexus:8081/nexus/content/groups/public/org/codehaus/mojo/maven-metadata.xml (20 KB at 28.6 KB/sec)
> [INFO] Downloaded: http://nexus:8081/nexus/content/groups/public/org/apache/maven/plugins/maven-metadata.xml (13 KB at 14.2 KB/sec)
> [INFO] Downloading: http://nexus:8081/nexus/content/groups/public/org/codehaus/mojo/sonar-maven-plugin/maven-metadata.xml
> [INFO] Downloaded: http://nexus:8081/nexus/content/groups/public/org/codehaus/mojo/sonar-maven-plugin/maven-metadata.xml (759 B at 2.1 KB/sec)
> [INFO] 
> [INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
> [INFO]  
> [INFO] ------------------------------------------------------------------------
> [INFO] Building ticket-monster 2.6.91-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [INFO] 
> [INFO] --- sonar-maven-plugin:2.6:sonar (default-cli) @ ticket-monster ---
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 2.662 s
> [INFO] Finished at: 2015-10-01T15:36:06+00:00
> [INFO] Final Memory: 16M/293M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.codehaus.mojo:sonar-maven-plugin:2.6:sonar (default-cli) on project ticket-monster: Execution default-cli of goal org.codehaus.mojo:sonar-maven-plugin:2.6:sonar failed: SonarQube server can not be reached at http://sonar:9000. Please check the parameter 'sonar.host.url'. -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:sonar-maven-plugin:2.6:sonar (default-cli) on project ticket-monster: Execution default-cli of goal org.codehaus.mojo:sonar-maven-plugin:2.6:sonar failed: SonarQube server can not be reached at http://sonar:9000. Please check the parameter 'sonar.host.url'.
>         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
>         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
>         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
>         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
>         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
>         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
>         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
>         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
>         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
>         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
>         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
>         at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:606)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
> Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.codehaus.mojo:sonar-maven-plugin:2.6:sonar failed: SonarQube server can not be reached at http://sonar:9000. Please check the parameter 'sonar.host.url'.
>         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:144)
>         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
>         ... 19 more
> Caused by: java.lang.IllegalStateException: SonarQube server can not be reached at http://sonar:9000. Please check the parameter 'sonar.host.url'.
>         at org.codehaus.mojo.sonar.ServerMetadata.getVersion(ServerMetadata.java:70)
>         at org.codehaus.mojo.sonar.ServerMetadata.logSettings(ServerMetadata.java:84)
>         at org.codehaus.mojo.sonar.SonarMojo.execute(SonarMojo.java:126)
>         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
>         ... 20 more
> Caused by: java.net.UnknownHostException: sonar
>         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
>         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
>         at java.net.Socket.connect(Socket.java:579)
>         at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
>         at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
>         at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
>         at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
>         at sun.net.www.http.HttpClient.New(HttpClient.java:308)
>         at sun.net.www.http.HttpClient.New(HttpClient.java:326)
>         at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:996)
>         at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
>         at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:850)
>         at org.codehaus.mojo.sonar.ServerMetadata.getConnection(ServerMetadata.java:119)
>         at org.codehaus.mojo.sonar.ServerMetadata.remoteContent(ServerMetadata.java:91)
>         at org.codehaus.mojo.sonar.ServerMetadata.getVersion(ServerMetadata.java:66)
>         ... 23 more
> [ERROR] 
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
> Sonar analysis completed: FAILURE
> Build step 'Sonar' changed build result to FAILURE
> Build step 'Sonar' marked build as failure
> # Finished: FAILURE
> # ERROR 2

Started by upstream project "ticket-monster-test-int" build number 3
originally caused by:
 Started by upstream project "ticket-monster-build" build number 3
 originally caused by:
  Started by user anonymous
Building in workspace /var/lib/jenkins/workspace/ticket-monster-release
Wiping out workspace first.
Cloning the remote Git repository
Cloning repository https://github.com/jbossdemocentral/continuous-delivery-demo-app.git

> git init /var/lib/jenkins/workspace/ticket-monster-release # timeout=10
> Fetching upstream changes from https://github.com/jbossdemocentral/continuous-delivery-demo-app.git
> git --version # timeout=10
> git fetch --tags --progress https://github.com/jbossdemocentral/continuous-delivery-demo-app.git +refs/heads/_:refs/remotes/origin/_
> git config remote.origin.url https://github.com/jbossdemocentral/continuous-delivery-demo-app.git # timeout=10
> git config remote.origin.fetch +refs/heads/_:refs/remotes/origin/_ # timeout=10
> git config remote.origin.url https://github.com/jbossdemocentral/continuous-delivery-demo-app.git # timeout=10
> Fetching upstream changes from https://github.com/jbossdemocentral/continuous-delivery-demo-app.git
> git fetch --tags --progress https://github.com/jbossdemocentral/continuous-delivery-demo-app.git +refs/heads/_:refs/remotes/origin/_
> git rev-parse origin/master^{commit} # timeout=10
> Checking out Revision 0b020609edac992a8ba94449d78a679b9eac02e7 (origin/master)
> git config core.sparsecheckout # timeout=10
> git checkout -f 0b020609edac992a8ba94449d78a679b9eac02e7 # timeout=10
> git branch -a # timeout=10
> git rev-parse remotes/origin/master^{commit} # timeout=10
> git rev-parse remotes/origin/test^{commit} # timeout=10
> git checkout -b master 0b020609edac992a8ba94449d78a679b9eac02e7
> git rev-list 0b020609edac992a8ba94449d78a679b9eac02e7 # timeout=10
> Parsing POMs
> [ticket-monster-release] $ /usr/lib/jvm/java-1.7.0/bin/java -cp /var/lib/jenkins/plugins/maven-plugin/WEB-INF/lib/maven31-agent-1.5.jar:/usr/share/apache-maven/boot/plexus-classworlds-2.5.1.jar:/usr/share/apache-maven/conf/logging jenkins.maven3.agent.Maven31Main /usr/share/apache-maven /var/cache/jenkins/war/WEB-INF/lib/remoting-2.47.jar /var/lib/jenkins/plugins/maven-plugin/WEB-INF/lib/maven31-interceptor-1.5.jar /var/lib/jenkins/plugins/maven-plugin/WEB-INF/lib/maven3-interceptor-commons-1.5.jar 60762
> <===[JENKINS REMOTING CAPACITY]===>���channel started
> Executing Maven:  -B -f /var/lib/jenkins/workspace/ticket-monster-release/pom.xml release:prepare release:perform --batch-mode
> [INFO] Scanning for projects...
> [INFO] 
> [INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
> [INFO]  
> [INFO] ------------------------------------------------------------------------
> [INFO] Building ticket-monster 2.6.91-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [INFO] 
> [INFO] --- maven-release-plugin:2.3.2:prepare (default-cli) @ ticket-monster ---
> [INFO] Verifying that there are no local modifications...
> [INFO]   ignoring changes on: *_/pom.xml.backup, *_/release.properties, *_/pom.xml.branch, *_/pom.xml.next, *_/pom.xml.releaseBackup, *_/pom.xml.tag
> [INFO] Executing: /bin/sh -c cd /var/lib/jenkins/workspace/ticket-monster-release && git status
> [INFO] Working directory: /var/lib/jenkins/workspace/ticket-monster-release
> [INFO] Checking dependencies and plugins for snapshots ...
> [INFO] Transforming 'ticket-monster'...
> [INFO] Not generating release POMs
> [INFO] Executing goals 'clean verify'...
> [INFO] [INFO] Scanning for projects...
> [INFO] [INFO] 
> [INFO] [INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
> [INFO] [INFO]  
> [INFO] [INFO] ------------------------------------------------------------------------
> [INFO] [INFO] Building ticket-monster 2.6.91
> [INFO] [INFO] ------------------------------------------------------------------------
> [INFO] [INFO] 
> [INFO] [INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ ticket-monster ---
> [INFO] [INFO] 
> [INFO] [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ ticket-monster ---
> [INFO] [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] [INFO] Copying 4 resources
> [INFO] [INFO] 
> [INFO] [INFO] --- maven-compiler-plugin:2.3.1:compile (default-compile) @ ticket-monster ---
> [INFO] [INFO] Compiling 84 source files to /var/lib/jenkins/workspace/ticket-monster-release/target/classes
> [INFO] [INFO] 
> [INFO] [INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ ticket-monster ---
> [INFO] [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] [INFO] Copying 3 resources
> [INFO] [INFO] 
> [INFO] [INFO] --- maven-compiler-plugin:2.3.1:testCompile (default-testCompile) @ ticket-monster ---
> [INFO] [INFO] Compiling 6 source files to /var/lib/jenkins/workspace/ticket-monster-release/target/test-classes
> [INFO] [INFO] 
> [INFO] [INFO] --- maven-surefire-plugin:2.4.3:test (default-test) @ ticket-monster ---
> [INFO] [INFO] Tests are skipped.
> [INFO] [INFO] 
> [INFO] [INFO] --- maven-war-plugin:2.1.1:war (default-war) @ ticket-monster ---
> [INFO] [INFO] Packaging webapp
> [INFO] [INFO] Assembling webapp [ticket-monster] in [/var/lib/jenkins/workspace/ticket-monster-release/target/ticket-monster]
> [INFO] [INFO] Processing war project
> [INFO] [INFO] Copying webapp resources [/var/lib/jenkins/workspace/ticket-monster-release/src/main/webapp]
> [INFO] [INFO] Webapp assembled in [111 msecs]
> [INFO] [INFO] Building war: /var/lib/jenkins/workspace/ticket-monster-release/target/ticket-monster.war
> [INFO] [INFO] ------------------------------------------------------------------------
> [INFO] [INFO] BUILD SUCCESS
> [INFO] [INFO] ------------------------------------------------------------------------
> [INFO] [INFO] Total time: 4.018 s
> [INFO] [INFO] Finished at: 2015-10-01T15:36:24+00:00
> [INFO] [INFO] Final Memory: 32M/415M
> [INFO] [INFO] ------------------------------------------------------------------------
> [INFO] Checking in modified POMs...
> [INFO] Executing: /bin/sh -c cd /var/lib/jenkins/workspace/ticket-monster-release && git add -- pom.xml
> [INFO] Working directory: /var/lib/jenkins/workspace/ticket-monster-release
> [INFO] Executing: /bin/sh -c cd /var/lib/jenkins/workspace/ticket-monster-release && git status
> [INFO] Working directory: /var/lib/jenkins/workspace/ticket-monster-release
> [INFO] Executing: /bin/sh -c cd /var/lib/jenkins/workspace/ticket-monster-release && git commit --verbose -F /tmp/maven-scm-812877236.commit pom.xml
> [INFO] Working directory: /var/lib/jenkins/workspace/ticket-monster-release
> [INFO] Executing: /bin/sh -c cd /var/lib/jenkins/workspace/ticket-monster-release && git symbolic-ref HEAD
> [INFO] Working directory: /var/lib/jenkins/workspace/ticket-monster-release
> [INFO] Executing: /bin/sh -c cd /var/lib/jenkins/workspace/ticket-monster-release && git push git@github.com:jbossdemocentral/continuous-delivery-demo-app.git master:master
> [INFO] Working directory: /var/lib/jenkins/workspace/ticket-monster-release
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 6.487 s
> [INFO] Finished at: 2015-10-01T15:36:24+00:00
> [INFO] Final Memory: 15M/293M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.3.2:prepare (default-cli) on project ticket-monster: Unable to commit files
> [ERROR] Provider message:
> [ERROR] The git-push command failed.
> [ERROR] Command output:
> [ERROR] Bad owner or permissions on /var/lib/jenkins/.ssh/config
> [ERROR] fatal: The remote end hung up unexpectedly
> [ERROR] -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> [JENKINS] Archiving /var/lib/jenkins/workspace/ticket-monster-release/pom.xml to org.jboss.examples/ticket-monster/2.6.91-SNAPSHOT/ticket-monster-2.6.91-SNAPSHOT.pom
> [ticket-monster-release] $ /bin/sh -xe /tmp/hudson2740922118650432954.sh
> channel stopped
> - echo ARTIFACT_VERSION=2.6.91
>   Warning: you have no plugins providing access control for builds, so falling back to legacy behavior of permitting any downstream builds to be triggered
>   Finished: FAILURE

**Comment by eschabell** [comment]
Passing on from ThomasQ:

"Hi John,

I suspect that you are having two isolated issues and the first is that the SonarCube docker image is a bit unstable. Restarting should solve the problem temporary.

The second one is probably my mistake for revoking access to a repo. In the release step I use maven to create a specific tag of my own clone of the ticket-monster demo. If you check the Jenkins job (the first job) you should be able to see the URL to the repo. My recommendation is that you clone the repo to your own github account and add the ssh key in the Jenkins docker image as a collaborator to that repo. Then change the Jenkins job to use your own repo.

Hope this help
Thomas"
